### ISSUE TITLE
Migrasi ke template v2 (astro)

### ISSUE THREAD

**Issue by mmdmthr** [mmdmthr/mmdmthr.github.io#181]
1. Copy semua artikel blog dari v1 ke v2
2. Selain artikel, pastikan juga SEO, header, title, informasi sosmed/about juga tercopy. Intinya semua konten harus sama persis.
1. Bagian yang perlu disesuaikan
    - date -> pubDate
    - category -> tags
    - description: ditambahkan → Berguna untuk SEO dan metadata Open Graph.
    - draft: bisa di-set true kalau kamu belum ingin post muncul di build produksi.
1. Test run dev

---

Secara prinsip, **alurmu sudah benar**, tapi ada beberapa **titik penting yang harus kamu perhatikan** biar transisi dari Gatsby ke Astro berjalan **tanpa error** dan **GitHub Actions langsung sukses nge-deploy**:

---

#### 1. **Ganti Semua File di Lokal**

* Hapus semua file proyek Gatsby (kecuali `.git/`)
* Inisialisasi proyek Astro di folder yang sama, atau copy hasil `npm create astro` ke folder repo lama.
* Jangan lupa tambahkan `package.json`, `astro.config.mjs`, dan `src/`, dll.

#### 2. **Update `.github/workflows/*.yml`**

* Ganti workflow `gatsby-deploy.yml` (atau sejenisnya) dengan workflow untuk **Astro + GitHub Pages**.
* Contoh workflow Astro yang umum:

```yaml
name: Deploy Astro to GitHub Pages

on:
  push:
    branches:
      - main  # Atau ganti dengan branch kamu

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
```

⚠️ Pastikan kamu sudah:

* Menambahkan `homepage` ke `astro.config.mjs` kalau repo kamu pakai subfolder (e.g. `https://username.github.io/repo-name`).
* Menggunakan branch `gh-pages` untuk hasil build (default untuk GitHub Pages).

---

### 3. **Test Lokal Dulu (Opsional Tapi Disarankan)**

```bash
npm install
npm run build
npm run preview
```

Pastikan tidak ada error dan `./dist` berisi hasil yang siap dideploy.

---

### 4. **Push ke Repo**

```bash
git add .
git commit -m "Migrate from Gatsby to Astro"
git push origin main
```

### 5. **GitHub Actions Akan Otomatis Jalan**

Workflow baru akan mendeteksi perubahan dan men-*trigger* build Astro → deploy ke branch `gh-pages`.

---

### 🧠 Catatan:

* Kalau sebelumnya kamu pakai plugin Gatsby khusus (image optimization, dsb), pastikan versi Astro-nya tidak kehilangan fitur penting.
* Kalau kamu deploy ke `username.github.io`, kamu harus build ke root (`/`) — **set `base` ke `"/"` di `astro.config.mjs`**.
* Kalau deploy ke subfolder (`username.github.io/blog`), set `base`:

  ```js
  export default defineConfig({
    base: '/blog/',
  })
  ```

---

Mau aku bantu review workflow yml kamu atau contohkan konfigurasi `astro.config.mjs` yang cocok untuk GitHub Pages?

<html><head></head><body><p>Karena kamu <strong>pakai <code>username.github.io</code></strong> (bukan subfolder repo), maka konfigurasi Astro kamu bisa tetap <strong>sederhana</strong> tanpa perlu <code>base</code> atau <code>site</code> yang disesuaikan. Tapi tetap ada beberapa hal penting untuk memastikan <strong>build-nya kompatibel dengan GitHub Pages</strong>.</p>
<hr>
<h3>✅ Contoh <code>astro.config.mjs</code> untuk GitHub Pages (<code>username.github.io</code>)</h3>
<pre><code class="language-js">import { defineConfig } from 'astro/config';

export default defineConfig({
  output: 'static', // untuk GitHub Pages (wajib)
  // Tidak perlu set `base` karena kamu di root domain
});
</code></pre>
<hr>
<h3>🧠 Penjelasan:</h3>

Properti | Nilai | Keterangan
-- | -- | --
output | 'static' | Wajib untuk GitHub Pages agar Astro membangun output 100% static HTML
base | ❌ (tidak perlu) | Karena kamu pakai username.github.io (root), tidak butuh base custom
site | ❌ (opsional) | Boleh diabaikan kecuali kamu ingin metadata otomatis seperti og:image dll

<hr>
<h3>🔒 Pastikan <code>astro.config.mjs</code> <strong>tidak kosong</strong>, karena tanpa <code>output: 'static'</code> build-nya bisa default ke SSR dan <strong>tidak cocok untuk GitHub Pages</strong>.</h3>
<hr>
